---
abstract: 'Adapter for Data::Semantic objects'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Domain-SemanticAdapter
provides:
  Data::Domain::SemanticAdapter:
    file: lib/Data/Domain/SemanticAdapter.pm
    version: 1.100840
  Data::Domain::SemanticAdapter::Test:
    file: lib/Data/Domain/SemanticAdapter/Test.pm
    version: 1.100840
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  Data::Domain: 0
  Data::Inherited: 0
  Data::Semantic::Test: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Hash::Rename: 0
  Scalar::Util: 0
  Test::More: 0.88
  UNIVERSAL::require: 0
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Domain-SemanticAdapter
  homepage: http://search.cpan.org/dist/Data-Domain-SemanticAdapter/
  repository: http://github.com/hanekomu/Data-Domain-SemanticAdapter
version: 1.100840
